services:
  postgres:
    image: timescale/timescaledb:latest-pg15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=beam_bot_dev
    ports:
      - "5465:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/postgres/002_add_custom_conf.sh:/docker-entrypoint-initdb.d/002_add_custom_conf.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: