services:
  questdb:
    image: questdb/questdb:latest
    container_name: questdb
    ports:
      - "9000:9000" # REST API and Web Console
      - "9009:9009" # PostgreSQL wire protocol
      - "8812:8812" # InfluxDB line protocol
    volumes:
      - questdb_data:/var/lib/questdb
    environment:
      - QDB_PG_WIRE_ENABLED=true
      - QDB_HTTP_ENABLED=true
      - QDB_LINE_TCP_ENABLED=true
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5439:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rustbot
    restart: unless-stopped

volumes:
  questdb_data:
  postgres_data:
